language: bash
services: docker

env:
  - VERSION=devel
  - VERSION=5.0
  - VERSION=4.4
  - VERSION=4.3
  - VERSION=4.2
  - VERSION=4.1
  - VERSION=4.0
  - VERSION=3.2
  - VERSION=3.1
  - VERSION=3.0

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "$VERSION"
  - image="bash:$VERSION"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      docker run -it --rm "$image" --version
      docker run -it --rm "$image" echo hi
      ~/official-images/test/run.sh "$image"
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
